### ISSUE TITLE
Tag patient drug-allergy records

### ISSUE THREAD

**Issue by Avalionnet** [AY2021S1-CS2103T-T12-4/tp#2]

**Comment by Avalionnet** [comment]
As a nurse, I can easily check the patient’s drug allergy history so that I can double-check if the medicines prescribed are not in the list.

**Comment by YangYue128-helen** [comment]
As a nurse, I can get an overview of the clinic’s appointment for the day.

**Comment by YangYue128-helen** [comment]
As a nurse, I can schedule my patient’s appointments easily without the tedious process involved in excel scheduling

**Comment by YangYue128-helen** [comment]
As a nurse, I am able to update patient’s details

**Comment by YangYue128-helen** [comment]
As a nurse, I am able to search for patient by name/phone number/patient id

**Comment by JinHao-L** [comment]
Implemented as tag during the creation of patient with `add`
